[versions]
ktor = "3.3.3"
komponenter = "1.0.461"
tilgang = "1.0.170"
behandlingsflyt = "0.0.508"
oppgave = "0.0.132"
utbetaling = "0.0.68"
postmottak = "6.0.2"

flyway = "11.19.0"

[libraries]
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktorServerHtmlBuilder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
motorTestUtils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgangKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }
utbetalKontrakt = { module = "no.nav.aap.utbetal:api-kontrakt", version.ref = "utbetaling" }
oppgaveKontrakt = { module = "no.nav.aap.oppgave:api-kontrakt", version.ref = "oppgave" }
postmottakKontrakt = { module = "no.nav.aap.postmottak:kontrakt", version.ref = "postmottak" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }
logbackLogstashEncoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "9.0" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway"}
flywayPostgres = {module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway"}
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.3" }

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }